name: allure-report
'on':
    push:
        branches:
            - master
jobs:
    generate-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2            
            - name: Prepare Allure history
              run: |
                  rm -r allure-results/*
                  cp -r ./allure-report/history ./allure-results/history
                  rm -r allure-report/*
            - name: Install Cypress
              run: |
                  npx cypress install
                  npx cypress cache list
                  
            - name: Run Cypress
              run: npm run test:allure

            - name: Generate Allure report
              if: always()
              uses: QuintilianoNery/action-allure-report-V2@0.2.0
